https://chatgpt.com/?utm_source=google&utm_medium=paid_search&utm_campaign=GOOG_C_SEM_GBR_Core_CHT_BAU_ACQ_PER_MIX_ALL_EMEA_ZA_EN_021425&c_id=22233293514&c_agid=178016288307&c_crid=733167304799&c_kwid=kwd-1927227100722&c_ims=&c_pms=1028666&c_nw=g&c_dvc=c&gad_source=1&gad_campaignid=22233293514&gbraid=0AAAAA-I0E5eL-jdei0OHjE69wnuZm5jfO&gclid=CjwKCAjw9szSBhBNEiwAC57Sq405djoWRxSLRsLGFPYtu3e4YgUq2Mr0cnRpqzEX3H-mIlFUWSXiExoCAW4QAvD_BwE

In [3]:
#Events endpoint
import pandas as pd

url = "http://data.gdeltproject.org/gdeltv2/lastupdate.txt"

# Read latest update information
latest = pd.read_csv(url, sep=" ", header=None)

'''
#debug-remove latter 
print(latest.head())
print(latest.dtypes)
# Events file URL (first .CSV.zip file containing "export")
events_url = latest[0][latest[0].str.contains("export")].iloc[0]

print(events_url)
'''

events_url = latest.loc[
    latest[2].str.contains("export", na=False),
    2
].iloc[0]

print(events_url)
events = pd.read_csv(
    events_url,
    sep="\t",
    header=None,
    compression="zip",
    low_memory=False
)

print(events.head())
print(events.shape)

http://data.gdeltproject.org/gdeltv2/20260712120000.export.CSV.zip
           0         1       2     3          4    5     6    7    8   9   \
0  1313237540  20260705  202607  2026  2026.5068  IRN  IRAN  IRN  NaN NaN
1  1313237541  20260705  202607  2026  2026.5068  IRN  IRAN  IRN  NaN NaN
2  1313237542  20260705  202607  2026  2026.5068  IRN  IRAN  IRN  NaN NaN
3  1313237543  20260705  202607  2026  2026.5068  IRN  IRAN  IRN  NaN NaN
4  1313237544  20260705  202607  2026  2026.5068  IRN  IRAN  IRN  NaN NaN

   ... 51      52  53  54   55    56     57  58              59  \
0  ...  1    Iran  IR  IR  NaN  32.0   53.0  IR  20260712120000
1  ...  1    Iran  IR  IR  NaN  32.0   53.0  IR  20260712120000
2  ...  1    Iran  IR  IR  NaN  32.0   53.0  IR  20260712120000
3  ...  1  Russia  RS  RS  NaN  60.0  100.0  RS  20260712120000
4  ...  1    Iran  IR  IR  NaN  32.0   53.0  IR  20260712120000

                                                  60
0  https://www.hindustantimes.com/world-news/laur...
1  https://www.hindustantimes.com/world-news/laur...
2  https://www.hindustantimes.com/world-news/laur...
3  https://www.hindustantimes.com/world-news/laur...
4  https://www.hindustantimes.com/world-news/laur...

[5 rows x 61 columns]
(681, 61)

In [ ]:
#events analysis

In [5]:
# Mentions endpoint
import pandas as pd

latest = pd.read_csv(
    "http://data.gdeltproject.org/gdeltv2/lastupdate.txt",
    sep=" ",
    header=None
)

mentions_url = latest.loc[
    latest[2].str.contains("mentions", na=False),
    2
].iloc[0]

print(mentions_url)

mentions = pd.read_csv(
    mentions_url,
    sep="\t",
    header=None,
    compression="zip",
    low_memory=False
)

print(mentions.head())
print(mentions.shape)

http://data.gdeltproject.org/gdeltv2/20260712121500.mentions.CSV.zip
           0               1               2   3                  4   \
0  1313238794  20260712121500  20260712121500   1       redstate.com
1  1313238795  20260712121500  20260712121500   1       redstate.com
2  1313220684  20260712083000  20260712121500   1  sitkasentinel.com
3  1251595839  20250712001500  20260712121500   1   semissourian.com
4  1313220685  20260712083000  20260712121500   1  sitkasentinel.com

                                                  5   6    7     8     9   10  \
0  https://redstate.com/redstate-guest-editorial/...   9   -1  2204  2258   0
1  https://redstate.com/redstate-guest-editorial/...   9   -1  2204  2222   0
2  http://www.sitkasentinel.com/stories/volkswage...   6  984    -1  1034   1
3  https://www.semissourian.com/world/volkswagen-...   3  468    -1   518   1
4  http://www.sitkasentinel.com/stories/volkswage...   6  984    -1  1027   1

    11    12        13  14  15
0   80  4153 -3.566334 NaN NaN
1   80  4153 -3.566334 NaN NaN
2  100  1178  0.500000 NaN NaN
3  100   667  0.833333 NaN NaN
4   50  1178  0.500000 NaN NaN
(2217, 16)

In [6]:
# GKG endpoint
import pandas as pd

latest = pd.read_csv(
    "http://data.gdeltproject.org/gdeltv2/lastupdate.txt",
    sep=" ",
    header=None
)

gkg_url = latest.loc[
    latest[2].str.contains("gkg", na=False),
    2
].iloc[0]

print(gkg_url)

gkg = pd.read_csv(
    gkg_url,
    sep="\t",
    header=None,
    compression="zip",
    low_memory=False
)

print(gkg.head())
print(gkg.shape)

http://data.gdeltproject.org/gdeltv2/20260712121500.gkg.csv.zip
                 0               1   2                      3   \
0  20260712121500-0  20260712121500   1          w4country.com
1  20260712121500-1  20260712121500   1          tvguide.co.uk
2  20260712121500-2  20260712121500   1         indiatimes.com
3  20260712121500-3  20260712121500   1  hurriyetdailynews.com
4  20260712121500-4  20260712121500   1     riotimesonline.com

                                                  4    5    6   \
0  https://www.w4country.com/2026/07/12/john-rich...  NaN  NaN
1  https://www.tvguide.co.uk/schedule/a0f3183d-3f...  NaN  NaN
2  https://timesofindia.indiatimes.com/defence/in...  NaN  NaN
3  https://www.hurriyetdailynews.com/major-german...  NaN  NaN
4  https://www.riotimesonline.com/world-cup-2026-...  NaN  NaN

                                                  7   \
0  TAX_FNCACT;TAX_FNCACT_ARTIST;APPOINTMENT;TAX_F...
1                                                NaN
2  TAX_ETHNICITY;TAX_ETHNICITY_CHINESE;TAX_WORLDL...
3  TAX_ETHNICITY;TAX_ETHNICITY_GERMAN;TAX_WORLDLA...
4                                                NaN

                                                  8   \
0  AGRICULTURE,155;AGRICULTURE,908;CRISISLEX_T11_...
1                                                NaN
2  TAX_FNCACT_GUARD,1216;TAX_FNCACT_GUARD,2088;TA...
3  TAX_ETHNICITY_CHINESE,47;TAX_ETHNICITY_CHINESE...
4                                                NaN

                                                  9   ...  \
0        1#United States#US#US#39.828175#-98.5795#US  ...
1                                                NaN  ...
2  4#Beijing, Beijing, China#CH#CH22#39.9289#116....  ...
3  4#Wolfsburg, Niedersachsen, Germany#GM#GM06#52...  ...
4  1#United States#US#US#39.828175#-98.5795#US;1#...  ...

                                                  17  \
0  wc:165,c1.1:1,c12.1:11,c12.10:17,c12.12:4,c12....
1  wc:94,c12.1:6,c12.10:16,c12.12:7,c12.13:8,c12....
2  wc:371,c12.1:3,c12.10:22,c12.12:6,c12.13:5,c12...
3  wc:466,c1.2:3,c1.3:2,c1.4:1,c12.1:19,c12.10:40...
4  wc:675,c12.1:35,c12.10:34,c12.12:14,c12.13:13,...

                                                  18   19   20   21   22  \
0  https://media-cdn.socastsrm.com/wordpress/wp-c...  NaN  NaN  NaN  NaN
1  https://tv.assets.pressassociation.io/83237009...  NaN  NaN  NaN  NaN
2  https://static.toiimg.com/thumb/msid-132344568...  NaN  NaN  NaN  NaN
3                                                NaN  NaN  NaN  NaN  NaN
4  https://www.riotimesonline.com/wp-content/uplo...  NaN  NaN  NaN  NaN

                                                  23  \
0  John Rich,31;Special Envoy,64;American Landown...
1  Dave Gorman,109;Omid Djalili,126;Davina McCall...
2  Liberation Army Navy,223;Taiwan The,613;Libera...
3  Major German,13;Lei Xing,1024;China Associatio...
4  Latin America,14;Latin America,94;Buenos Aires...

                                                  24  25  \
0                                                NaN NaN
1                     3,Episode 6 of 9,59;6,of 9,67; NaN
2                                                NaN NaN
3                                  300,vehicles,956; NaN
4  26,exchanges,161;3000000,Eastern,423;3000000,E... NaN

                                                  26
0  <PAGE_PRECISEPUBTIMESTAMP>20260712085700</PAGE...
1  <PAGE_LINKS>https://www.tvguide.co.uk/channel/...
2  <PAGE_ALTURL_AMP>https://timesofindia.indiatim...
3  <PAGE_LINKS>https://www.hurriyetdailynews.com/...
4  <PAGE_LINKS>https://www.riotimesonline.com/bra...

[5 rows x 27 columns]
(698, 27)

In [ ]:
#uniue sources represented
gkg[3].nunique()

160

In [11]:
#top domains
gkg[3].value_counts().head(10)

3
tvguide.co.uk          72
indiatimes.com         26
riotimesonline.com     20
bignewsnetwork.com     19
newsghana.com.gh       19
tribuneonlineng.com    17
express.co.uk          17
unitaid.eu             16
newkerala.com          15
liverpoolecho.co.uk    11
Name: count, dtype: int64

In [12]:
#Number of articles containing themes
gkg[7].notna().sum()

np.int64(604)

In [17]:
#Give the columns names (Events)
events = events.rename(columns={
    0: "GLOBALEVENTID",
    1: "SQLDATE",
    2: "MonthYear",
    3: "Year",
    4: "FractionDate",
    5: "Actor1Code",
    6: "Actor1Name",
    7: "Actor1CountryCode",
    15: "Actor2Code",
    16: "Actor2Name",
    17: "Actor2CountryCode",
    26: "EventCode",
    27: "EventBaseCode",
    28: "EventRootCode",
    29: "QuadClass",
    30: "GoldsteinScale",
    31: "NumMentions",
    32: "NumSources",
    33: "NumArticles",
    34: "AvgTone",
    60: "SOURCEURL"
})

In [18]:
events.head()

,GLOBALEVENTID,SQLDATE,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,8,9,...,51,52,53,54,55,56,57,58,59,SOURCEURL
0,1313237540,20260705,202607,2026,2026.5068,IRN,IRAN,IRN,NaN,NaN,...,1,Iran,IR,IR,NaN,32.0,53.0,IR,20260712120000,https://www.hindustantimes.com/world-news/laur...
1,1313237541,20260705,202607,2026,2026.5068,IRN,IRAN,IRN,NaN,NaN,...,1,Iran,IR,IR,NaN,32.0,53.0,IR,20260712120000,https://www.hindustantimes.com/world-news/laur...
2,1313237542,20260705,202607,2026,2026.5068,IRN,IRAN,IRN,NaN,NaN,...,1,Iran,IR,IR,NaN,32.0,53.0,IR,20260712120000,https://www.hindustantimes.com/world-news/laur...
3,1313237543,20260705,202607,2026,2026.5068,IRN,IRAN,IRN,NaN,NaN,...,1,Russia,RS,RS,NaN,60.0,100.0,RS,20260712120000,https://www.hindustantimes.com/world-news/laur...
4,1313237544,20260705,202607,2026,2026.5068,IRN,IRAN,IRN,NaN,NaN,...,1,Iran,IR,IR,NaN,32.0,53.0,IR,20260712120000,https://www.hindustantimes.com/world-news/laur...

In [19]:
mentions.columns = [
    "GLOBALEVENTID",
    "EventTimeDate",
    "MentionTimeDate",
    "MentionType",
    "SourceName",
    "DocumentIdentifier",
    "SentenceID",
    "Actor1CharOffset",
    "Actor2CharOffset",
    "ActionCharOffset",
    "InRawText",
    "Confidence",
    "MentionDocLen",
    "MentionDocTone",
    "MentionDocTranslationInfo",
    "Extras"
]

In [20]:
mentions.head()

,GLOBALEVENTID,EventTimeDate,MentionTimeDate,MentionType,SourceName,DocumentIdentifier,SentenceID,Actor1CharOffset,Actor2CharOffset,ActionCharOffset,InRawText,Confidence,MentionDocLen,MentionDocTone,MentionDocTranslationInfo,Extras
0,1313238794,20260712121500,20260712121500,1,redstate.com,https://redstate.com/redstate-guest-editorial/...,9,-1,2204,2258,0,80,4153,-3.566334,NaN,NaN
1,1313238795,20260712121500,20260712121500,1,redstate.com,https://redstate.com/redstate-guest-editorial/...,9,-1,2204,2222,0,80,4153,-3.566334,NaN,NaN
2,1313220684,20260712083000,20260712121500,1,sitkasentinel.com,http://www.sitkasentinel.com/stories/volkswage...,6,984,-1,1034,1,100,1178,0.500000,NaN,NaN
3,1251595839,20250712001500,20260712121500,1,semissourian.com,https://www.semissourian.com/world/volkswagen-...,3,468,-1,518,1,100,667,0.833333,NaN,NaN
4,1313220685,20260712083000,20260712121500,1,sitkasentinel.com,http://www.sitkasentinel.com/stories/volkswage...,6,984,-1,1027,1,50,1178,0.500000,NaN,NaN

In [22]:
gkg = gkg.rename(columns={
    0: "GKGRECORDID",
    1: "DATE",
    2: "SourceCollectionIdentifier",
    3: "SourceCommonName",
    4: "DocumentIdentifier",
    7: "Themes",
    8: "ThemeCounts",
    9: "Locations",
    17: "Tone",
    18: "ImageURL",
    23: "Names",
    26: "Metadata"
})

In [23]:
print(gkg.shape)

(698, 27)

In [24]:
print(len(gkg.columns))

27

In [25]:
print(events.shape)
print(mentions.shape)
print(gkg.shape)

(681, 61)
(2217, 16)
(698, 27)

In [ ]:
events_mentions = events.merge(
    mentions,
    on="GLOBALEVENTID",
    how="left"
)

In [26]:
events_mentions.head()

NameError: name 'events_mentions' is not defined

In [ ]:
#Filter by country
sa = events[
    events["Actor1CountryCode"] == "SF"
]

print(sa[[
    "Actor1Name",
    "Actor2Name",
    "AvgTone",
    "SOURCEURL"
]].head())

In [ ]:
#filter by sentiment
negative = events[
    events["AvgTone"] < -5
]

print(negative.head())

In [ ]:
#Search GKG themes
health = gkg[
    gkg[8].str.contains(
        "HEALTH",
        case=False,
        na=False
    )
]

print(health.head())

In [ ]:
#Search for organizations
world_bank = gkg[
    gkg[14].str.contains(
        "World Bank",
        case=False,
        na=False
    )
]

print(world_bank.head())